// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(client) {
    return client.addCommand('goUrl', function(url, force, cb) {
      return client.url(url).url(function(err, res) {
        console.log(res.value, url);
        assert.isNull(err);
        if (force) {
          assert.equal(res.value, url, "Wrong destination url");
        }
        return cb();
      });
    });
  };

}).call(this);

//# sourceMappingURL=commands.js.map
